### ISSUE TITLE
"path" is overridden by fireplace rather extending

### ISSUE THREAD

**Issue by manawardhana** [tpope/vim-fireplace#283]
I want to use `:search` in sub directories. So I set
`:set path+=**`
and it is working.

But once I loaded a clojure file, fireplace is replacing my values set for the `path`. So that I need to use the above command for each file load.

This is not happening when vim-fireplace is disabled.

**Comment by tpope** [comment]
Fireplace uses `'path'` for it's intended purpose of containing a load path (in this case the JVM class path) which is core to how built-ins like `]d` and `gf` work as well as to Fireplace's enhanced remaps. I would expect adding `**` to introduce numerous subtle bugs, so I won't be changing this.

Rather than twisting `:find` to your needs, I would encourage you to look at a proper fuzzy finder plugin like ctrl-p instead. If your really want to force the issue, changing `'path'` in `after/ftplugin/clojure.vim`.

**Comment by tpope** [comment]
Actually, I think technically, Fireplace bends over backwards to avoid stepping on `'path'`, but it will use it for offline evaluation if another plugin like salve.vim or classpath.vim sets it. Argument still basically applies, but "numerous subtle bugs" might be an exaggeration.
