### ISSUE TITLE
Connecting to remote repl (docker) can't find sources

### ISSUE THREAD

**Issue by fuadsaud** [tpope/vim-fireplace#288]
I'm running vim on my laptop and connection to a repl running in a docker container.

I can successfully `:Connect hostname:port`, open the quasi-repl and Eval expressions. However, when I try `[<C-d>` or `:Source ` and `:Doc` from my source code, I get `Couldn't find source for ...`. Running `(source <symbol>)` in the quasi-repl and supplying the exact same symbols from the source files returns the symbol's definition successfully, so I can attest it is able to connect and locate things.

I'm not sure how I can further debug this issue, since fireplace does not spit any detailed logs. I'm also not sure if I can get the nrepl server to get any more verbose, in order to know exactly what fireplace is sending to and getting back from it.

**Comment by tpope** [comment]
* `:Source` literally calls `clojure.repl/source`. I don't see much that could go wrong unless cljs is in the mix. 
* `:Doc` uses CIDER if available, otherwise falls back to `clojure.repl/doc`.
* `[<C-d>` uses CIDER or an eval to get a relative filename, then hunts for it in `'path'`. Check that `:verbose set path?` looks like an appropriate class path for your system (outside the container, not in it).
